### ISSUE TITLE
9/26 TODO

### ISSUE THREAD

**Issue by Joyykim** [YogiyoCloneTeamProject/YogiYoCloneAPI#107]
### 사라
- [x] 검색 api 추가 - icontains

### 주원
- [x] 회원가입 로직 수정 - email, password, nick_name만 POST해서 비활성 유저 생성 후 iOS에서 전화번호 인증되면 PATCH해서 유저 활성
- [x] 마이페이지 - nick_name, phone_number 필드 추가
