### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Joyykim** [YogiyoCloneTeamProject/YogiYoCloneAPI#126]
- [ ]  검색 api - fulltext
- [ ]  검색 - 자동 완성 키워드: 태그를 레스토랑에 추가, 텍스트 칠 때 icontains로 태그 리스트 리턴, 검색 시 태그로 검색 - taggit
- [ ]  크롤링 데이터 추가
- [ ]  회원가입 도중에 나갈때 예외 처리 - user삭제
- [ ]  찜 api, 테코
- [ ]  나머지 api 테스트코드 추가
- [ ]  admin 개발 - 모델 추가 등
- [ ]  크롤링 데이터 더 추가, PAGE_SIZE 50개 정도?
- [ ]  최적화, 고도화
